/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ecoscore;

import javax.swing.*;
import java.awt.*;

// imports class necessary to deal with exceptions
import java.io.IOException;

/**
 *
 * @author emilychappel
 */
public class EcoScoreApp extends javax.swing.JFrame {
    
    // custom method to scale image
    private ImageIcon scaleImage(ImageIcon originalIcon, int scaledWidth, int scaledHeight) {
        Image image = originalIcon.getImage();
        Image scaledImage = image.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);
        return new ImageIcon(scaledImage);
    }

    /**
     * Creates new form EcoScoreApp
     */
    public EcoScoreApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText6 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        inputGasBill1 = new javax.swing.JTextField();
        btnExitTab5 = new javax.swing.JButton();
        btnToTab5 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        titleText2 = new javax.swing.JLabel();
        titleText3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnToTab2 = new javax.swing.JButton();
        btnLearnMore = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titleText4 = new javax.swing.JLabel();
        inputElectricBill = new javax.swing.JTextField();
        btnToTab3 = new javax.swing.JButton();
        text4 = new javax.swing.JLabel();
        btnExitTab2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        text5 = new javax.swing.JLabel();
        inputGasBill = new javax.swing.JTextField();
        btnToTab4 = new javax.swing.JButton();
        titleText5 = new javax.swing.JLabel();
        btnExitTab3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        titleText7 = new javax.swing.JLabel();
        text7 = new javax.swing.JLabel();
        inputGasBill2 = new javax.swing.JTextField();
        btnNextToTab5 = new javax.swing.JButton();
        btnExitTab4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        titleText9 = new javax.swing.JLabel();
        text9 = new javax.swing.JLabel();
        inputGasBill4 = new javax.swing.JTextField();
        btnNextToTab6 = new javax.swing.JButton();
        btnExitOnTab5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        text10 = new javax.swing.JLabel();
        inputGasBill5 = new javax.swing.JTextField();
        btnNextToTab7 = new javax.swing.JButton();
        btnExitOnTab6 = new javax.swing.JButton();
        titleText15 = new javax.swing.JLabel();
        titleText16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        titleText11 = new javax.swing.JLabel();
        text11 = new javax.swing.JLabel();
        inputGasBill6 = new javax.swing.JTextField();
        btnNextToTab8 = new javax.swing.JButton();
        btnExitOnTab7 = new javax.swing.JButton();
        titleText14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        titleText12 = new javax.swing.JLabel();
        btnNextToTab9 = new javax.swing.JButton();
        btnExitOnTab8 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        btnNextToTab10 = new javax.swing.JButton();
        btnExitOnTab9 = new javax.swing.JButton();
        titleText17 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        titleText18 = new javax.swing.JLabel();
        btnLearnMore2 = new javax.swing.JButton();
        btnToTab12 = new javax.swing.JButton();
        btnToTab11 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        titleText19 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        titleText20 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        titleText21 = new javax.swing.JLabel();

        titleText6.setFont(new java.awt.Font("Arial Hebrew Scholar", 1, 36)); // NOI18N
        titleText6.setText("What is your monthly gas bill?");

        text6.setText("Please enter an integer");

        inputGasBill1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputGasBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGasBill1ActionPerformed(evt);
            }
        });

        btnExitTab5.setBackground(new java.awt.Color(250, 91, 60));
        btnExitTab5.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExitTab5.setForeground(new java.awt.Color(255, 255, 255));
        btnExitTab5.setText("EXIT");
        btnExitTab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitTab5ActionPerformed(evt);
            }
        });

        btnToTab5.setBackground(new java.awt.Color(5, 102, 8));
        btnToTab5.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnToTab5.setForeground(new java.awt.Color(240, 240, 240));
        btnToTab5.setText("NEXT");
        btnToTab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToTab5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 194, 43));

        titleText2.setFont(new java.awt.Font("Impact", 0, 56)); // NOI18N
        titleText2.setText("HOW BIG IS YOUR");

        titleText3.setFont(new java.awt.Font("Impact", 0, 56)); // NOI18N
        titleText3.setText("CARBON FOOTPRINT?");

        label2.setText("Our world is in crisis, and it's up to all of us to fix it. Take your first step");

        label3.setText("with our carbon footprint calculator.");

        btnExit.setBackground(new java.awt.Color(250, 91, 60));
        btnExit.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnToTab2.setBackground(new java.awt.Color(0, 0, 0));
        btnToTab2.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnToTab2.setForeground(new java.awt.Color(240, 240, 240));
        btnToTab2.setText("GET STARTED");
        btnToTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToTab2ActionPerformed(evt);
            }
        });

        btnLearnMore.setBackground(new java.awt.Color(100, 149, 237));
        btnLearnMore.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnLearnMore.setForeground(new java.awt.Color(240, 240, 240));
        btnLearnMore.setText("LEARN MORE!");
        btnLearnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnMoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleText3)
                    .addComponent(titleText2)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnToTab2)
                        .addGap(18, 18, 18)
                        .addComponent(btnLearnMore)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleText3)
                .addGap(18, 18, 18)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToTab2)
                    .addComponent(btnLearnMore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(150, 194, 43));

        titleText4.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText4.setText("What is your monthly electric bill?");

        inputElectricBill.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputElectricBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputElectricBillActionPerformed(evt);
            }
        });

        btnToTab3.setBackground(new java.awt.Color(5, 102, 8));
        btnToTab3.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnToTab3.setForeground(new java.awt.Color(240, 240, 240));
        btnToTab3.setText("NEXT");
        btnToTab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToTab3ActionPerformed(evt);
            }
        });

        text4.setText("Please enter an integer");

        btnExitTab2.setBackground(new java.awt.Color(250, 91, 60));
        btnExitTab2.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExitTab2.setForeground(new java.awt.Color(255, 255, 255));
        btnExitTab2.setText("EXIT");
        btnExitTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitTab2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnExitTab2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text4)
                            .addComponent(titleText4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inputElectricBill, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnToTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleText4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(text4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputElectricBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToTab3))
                .addGap(18, 18, 18)
                .addComponent(btnExitTab2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(150, 194, 43));

        text5.setText("Please enter an integer");

        inputGasBill.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputGasBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGasBillActionPerformed(evt);
            }
        });

        btnToTab4.setBackground(new java.awt.Color(5, 102, 8));
        btnToTab4.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnToTab4.setForeground(new java.awt.Color(240, 240, 240));
        btnToTab4.setText("NEXT");
        btnToTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToTab4ActionPerformed(evt);
            }
        });

        titleText5.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText5.setText("What is your monthly gas bill?");

        btnExitTab3.setBackground(new java.awt.Color(250, 91, 60));
        btnExitTab3.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExitTab3.setForeground(new java.awt.Color(255, 255, 255));
        btnExitTab3.setText("EXIT");
        btnExitTab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitTab3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnExitTab3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(titleText5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(text5)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(inputGasBill, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(btnToTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleText5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExitTab3)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputGasBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnToTab4))
                    .addGap(64, 64, 64)))
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel4.setBackground(new java.awt.Color(150, 194, 43));

        titleText7.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText7.setText("What is your monthly oil bill?");

        text7.setText("Please enter an integer");

        inputGasBill2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputGasBill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGasBill2ActionPerformed(evt);
            }
        });

        btnNextToTab5.setBackground(new java.awt.Color(5, 102, 8));
        btnNextToTab5.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnNextToTab5.setForeground(new java.awt.Color(240, 240, 240));
        btnNextToTab5.setText("NEXT");
        btnNextToTab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextToTab5ActionPerformed(evt);
            }
        });

        btnExitTab4.setBackground(new java.awt.Color(250, 91, 60));
        btnExitTab4.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExitTab4.setForeground(new java.awt.Color(255, 255, 255));
        btnExitTab4.setText("EXIT");
        btnExitTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitTab4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(inputGasBill2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNextToTab5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(text7)
                            .addComponent(titleText7)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnExitTab4)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleText7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(text7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputGasBill2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextToTab5))
                .addGap(33, 33, 33)
                .addComponent(btnExitTab4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        jPanel5.setBackground(new java.awt.Color(150, 194, 43));

        titleText9.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText9.setText("What is the yearly mileage on your car?");

        text9.setText("Please enter an integer");

        inputGasBill4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputGasBill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGasBill4ActionPerformed(evt);
            }
        });

        btnNextToTab6.setBackground(new java.awt.Color(5, 102, 8));
        btnNextToTab6.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnNextToTab6.setForeground(new java.awt.Color(240, 240, 240));
        btnNextToTab6.setText("NEXT");
        btnNextToTab6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextToTab6ActionPerformed(evt);
            }
        });

        btnExitOnTab5.setBackground(new java.awt.Color(250, 91, 60));
        btnExitOnTab5.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExitOnTab5.setForeground(new java.awt.Color(255, 255, 255));
        btnExitOnTab5.setText("EXIT");
        btnExitOnTab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitOnTab5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(inputGasBill4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNextToTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(text9)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnExitOnTab5)))
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titleText9, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleText9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addComponent(text9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputGasBill4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextToTab6))
                .addGap(33, 33, 33)
                .addComponent(btnExitOnTab5)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab5", jPanel5);

        jPanel6.setBackground(new java.awt.Color(150, 194, 43));

        text10.setText("Please enter an integer");

        inputGasBill5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputGasBill5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGasBill5ActionPerformed(evt);
            }
        });

        btnNextToTab7.setBackground(new java.awt.Color(5, 102, 8));
        btnNextToTab7.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnNextToTab7.setForeground(new java.awt.Color(240, 240, 240));
        btnNextToTab7.setText("NEXT");
        btnNextToTab7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextToTab7ActionPerformed(evt);
            }
        });

        btnExitOnTab6.setBackground(new java.awt.Color(250, 91, 60));
        btnExitOnTab6.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExitOnTab6.setForeground(new java.awt.Color(255, 255, 255));
        btnExitOnTab6.setText("EXIT");
        btnExitOnTab6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitOnTab6ActionPerformed(evt);
            }
        });

        titleText15.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText15.setText("How many flights <4 hours have you ");

        titleText16.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText16.setText("been on in the past year?");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(inputGasBill5, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNextToTab7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(text10)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnExitOnTab6)))
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleText15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleText16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleText15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleText16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addComponent(text10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputGasBill5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextToTab7))
                .addGap(33, 33, 33)
                .addComponent(btnExitOnTab6)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab6", jPanel6);

        jPanel7.setBackground(new java.awt.Color(150, 194, 43));

        titleText11.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText11.setText("been on in the past year?");

        text11.setText("Please enter an integer");

        inputGasBill6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        inputGasBill6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGasBill6ActionPerformed(evt);
            }
        });

        btnNextToTab8.setBackground(new java.awt.Color(5, 102, 8));
        btnNextToTab8.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnNextToTab8.setForeground(new java.awt.Color(240, 240, 240));
        btnNextToTab8.setText("NEXT");
        btnNextToTab8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextToTab8ActionPerformed(evt);
            }
        });

        btnExitOnTab7.setBackground(new java.awt.Color(250, 91, 60));
        btnExitOnTab7.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExitOnTab7.setForeground(new java.awt.Color(255, 255, 255));
        btnExitOnTab7.setText("EXIT");
        btnExitOnTab7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitOnTab7ActionPerformed(evt);
            }
        });

        titleText14.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText14.setText("How many flights >4 hours have you ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(inputGasBill6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNextToTab8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(text11)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnExitOnTab7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titleText14, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(titleText11, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleText14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleText11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(text11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputGasBill6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextToTab8))
                .addGap(33, 33, 33)
                .addComponent(btnExitOnTab7)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab7", jPanel7);

        jPanel8.setBackground(new java.awt.Color(150, 194, 43));

        titleText12.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText12.setText("Do you recycle newspaper?");

        btnNextToTab9.setBackground(new java.awt.Color(5, 102, 8));
        btnNextToTab9.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnNextToTab9.setForeground(new java.awt.Color(240, 240, 240));
        btnNextToTab9.setText("NEXT");
        btnNextToTab9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextToTab9ActionPerformed(evt);
            }
        });

        btnExitOnTab8.setBackground(new java.awt.Color(250, 91, 60));
        btnExitOnTab8.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExitOnTab8.setForeground(new java.awt.Color(255, 255, 255));
        btnExitOnTab8.setText("EXIT");
        btnExitOnTab8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitOnTab8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Yes");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("No");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(489, 489, 489)
                                .addComponent(btnNextToTab9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnExitOnTab8)))
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titleText12, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleText12)
                .addGap(102, 102, 102)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(btnNextToTab9)
                .addGap(33, 33, 33)
                .addComponent(btnExitOnTab8)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab8", jPanel8);

        jPanel9.setBackground(new java.awt.Color(150, 194, 43));

        btnNextToTab10.setBackground(new java.awt.Color(5, 102, 8));
        btnNextToTab10.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnNextToTab10.setForeground(new java.awt.Color(240, 240, 240));
        btnNextToTab10.setText("SUBMIT");
        btnNextToTab10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextToTab10ActionPerformed(evt);
            }
        });

        btnExitOnTab9.setBackground(new java.awt.Color(250, 91, 60));
        btnExitOnTab9.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        btnExitOnTab9.setForeground(new java.awt.Color(255, 255, 255));
        btnExitOnTab9.setText("EXIT");
        btnExitOnTab9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitOnTab9ActionPerformed(evt);
            }
        });

        titleText17.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText17.setText("Do you recycle aluminium?");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Yes");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("No");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnExitOnTab9))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(btnNextToTab10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(titleText17, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(352, 352, 352)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton3))
                    .addContainerGap(352, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleText17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                .addComponent(btnNextToTab10)
                .addGap(33, 33, 33)
                .addComponent(btnExitOnTab9)
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(263, 263, 263)
                    .addComponent(jRadioButton3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRadioButton4)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab9", jPanel9);

        jPanel10.setBackground(new java.awt.Color(150, 194, 43));

        titleText18.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText18.setText("Your results:");

        btnLearnMore2.setBackground(new java.awt.Color(100, 149, 237));
        btnLearnMore2.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnLearnMore2.setForeground(new java.awt.Color(240, 240, 240));
        btnLearnMore2.setText("LEARN MORE!");
        btnLearnMore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnMore2ActionPerformed(evt);
            }
        });

        btnToTab12.setBackground(new java.awt.Color(5, 102, 8));
        btnToTab12.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnToTab12.setForeground(new java.awt.Color(240, 240, 240));
        btnToTab12.setText("SET GOALS");
        btnToTab12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToTab12ActionPerformed(evt);
            }
        });

        btnToTab11.setBackground(new java.awt.Color(0, 0, 0));
        btnToTab11.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        btnToTab11.setForeground(new java.awt.Color(240, 240, 240));
        btnToTab11.setText("RECOMMENDATIONS");
        btnToTab11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToTab11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnToTab11)
                        .addGap(18, 18, 18)
                        .addComponent(btnToTab12, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLearnMore2))
                    .addComponent(titleText18, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleText18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLearnMore2)
                    .addComponent(btnToTab12)
                    .addComponent(btnToTab11))
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("tab10", jPanel10);

        jPanel11.setBackground(new java.awt.Color(150, 194, 43));

        titleText19.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText19.setText("What can you do?");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(titleText19, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleText19)
                .addContainerGap(510, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab11", jPanel11);

        jPanel12.setBackground(new java.awt.Color(150, 194, 43));

        titleText20.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText20.setText("Set your own goals:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(titleText20, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleText20)
                .addContainerGap(510, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab12", jPanel12);

        jPanel13.setBackground(new java.awt.Color(150, 194, 43));

        titleText21.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        titleText21.setText("Learn more!");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(titleText21, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleText21)
                .addContainerGap(510, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab13", jPanel13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputGasBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGasBill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGasBill1ActionPerformed

    private void btnExitTab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTab5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitTab5ActionPerformed

    private void btnToTab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToTab5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToTab5ActionPerformed

    private void btnExitOnTab8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitOnTab8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitOnTab8ActionPerformed

    private void btnNextToTab9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextToTab9ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(8);
    }//GEN-LAST:event_btnNextToTab9ActionPerformed

    private void btnExitOnTab7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitOnTab7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitOnTab7ActionPerformed

    private void btnNextToTab8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextToTab8ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_btnNextToTab8ActionPerformed

    private void inputGasBill6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGasBill6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGasBill6ActionPerformed

    private void btnExitOnTab6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitOnTab6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitOnTab6ActionPerformed

    private void btnNextToTab7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextToTab7ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_btnNextToTab7ActionPerformed

    private void inputGasBill5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGasBill5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGasBill5ActionPerformed

    private void btnExitOnTab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitOnTab5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitOnTab5ActionPerformed

    private void btnNextToTab6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextToTab6ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_btnNextToTab6ActionPerformed

    private void inputGasBill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGasBill4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGasBill4ActionPerformed

    private void btnExitTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTab4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitTab4ActionPerformed

    private void btnNextToTab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextToTab5ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnNextToTab5ActionPerformed

    private void inputGasBill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGasBill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGasBill2ActionPerformed

    private void btnExitTab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTab3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitTab3ActionPerformed

    private void btnToTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToTab4ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnToTab4ActionPerformed

    private void inputGasBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGasBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGasBillActionPerformed

    private void btnExitTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTab2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitTab2ActionPerformed

    private void btnToTab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToTab3ActionPerformed
        // TODO add your handling code here:

        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnToTab3ActionPerformed

    private void inputElectricBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputElectricBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputElectricBillActionPerformed

    private void btnLearnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnMoreActionPerformed
        // TODO add your handling code here:

        jTabbedPane1.setSelectedIndex(12);
    }//GEN-LAST:event_btnLearnMoreActionPerformed

    private void btnToTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToTab2ActionPerformed
        // TODO add your handling code here:

        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnToTab2ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitOnTab9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitOnTab9ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btnExitOnTab9ActionPerformed

    private void btnNextToTab10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextToTab10ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(9);
    }//GEN-LAST:event_btnNextToTab10ActionPerformed

    private void btnLearnMore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnMore2ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(12);
    }//GEN-LAST:event_btnLearnMore2ActionPerformed

    private void btnToTab12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToTab12ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(11);
    }//GEN-LAST:event_btnToTab12ActionPerformed

    private void btnToTab11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToTab11ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(10);
    }//GEN-LAST:event_btnToTab11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcoScoreApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcoScoreApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcoScoreApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcoScoreApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcoScoreApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExitOnTab5;
    private javax.swing.JButton btnExitOnTab6;
    private javax.swing.JButton btnExitOnTab7;
    private javax.swing.JButton btnExitOnTab8;
    private javax.swing.JButton btnExitOnTab9;
    private javax.swing.JButton btnExitTab2;
    private javax.swing.JButton btnExitTab3;
    private javax.swing.JButton btnExitTab4;
    private javax.swing.JButton btnExitTab5;
    private javax.swing.JButton btnLearnMore;
    private javax.swing.JButton btnLearnMore2;
    private javax.swing.JButton btnNextToTab10;
    private javax.swing.JButton btnNextToTab5;
    private javax.swing.JButton btnNextToTab6;
    private javax.swing.JButton btnNextToTab7;
    private javax.swing.JButton btnNextToTab8;
    private javax.swing.JButton btnNextToTab9;
    private javax.swing.JButton btnToTab11;
    private javax.swing.JButton btnToTab12;
    private javax.swing.JButton btnToTab2;
    private javax.swing.JButton btnToTab3;
    private javax.swing.JButton btnToTab4;
    private javax.swing.JButton btnToTab5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField inputElectricBill;
    private javax.swing.JTextField inputGasBill;
    private javax.swing.JTextField inputGasBill1;
    private javax.swing.JTextField inputGasBill2;
    private javax.swing.JTextField inputGasBill4;
    private javax.swing.JTextField inputGasBill5;
    private javax.swing.JTextField inputGasBill6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel text10;
    private javax.swing.JLabel text11;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel text7;
    private javax.swing.JLabel text9;
    private javax.swing.JLabel titleText11;
    private javax.swing.JLabel titleText12;
    private javax.swing.JLabel titleText14;
    private javax.swing.JLabel titleText15;
    private javax.swing.JLabel titleText16;
    private javax.swing.JLabel titleText17;
    private javax.swing.JLabel titleText18;
    private javax.swing.JLabel titleText19;
    private javax.swing.JLabel titleText2;
    private javax.swing.JLabel titleText20;
    private javax.swing.JLabel titleText21;
    private javax.swing.JLabel titleText3;
    private javax.swing.JLabel titleText4;
    private javax.swing.JLabel titleText5;
    private javax.swing.JLabel titleText6;
    private javax.swing.JLabel titleText7;
    private javax.swing.JLabel titleText9;
    // End of variables declaration//GEN-END:variables
}
